Bomberman/Models/Games.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Games_details = new HashSet<Games_details>();
            this.Games_requests = new HashSet<Games_requests>();
            this.Users_play = new HashSet<Users_play>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_map { get; set; }
        public int remaining_time { get; set; }
        public bool is_public { get; set; }
        public int owner { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Games_details> Games_details { get; set; }
        public virtual Maps Maps { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Games_requests> Games_requests { get; set; }
        public virtual ICollection<Users_play> Users_play { get; set; }
    }
}

Bomberman/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bomberman.Filters;
using Bomberman.Models;
using System.Runtime.Serialization.Json;
using System.IO;
using System.Text;
using System.Collections;

namespace Bomberman.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class GameController : Controller
    {

        private BOMBERMANEntities db = new BOMBERMANEntities();


        [AllowAnonymous]
        public ActionResult PublicList()
        {

           

                IList<Games> games = null;



                var query = (from g in db.Games
                             where g.is_public == true
                             select g).Include("UserProfile").Include("Maps");

                games = query.ToList<Games>();


                return View(games);
            



        }



        public ActionResult LetsPlay(int id = 0)
        {

           
                Games games = db.Games.Find(id);
                if (games == null)
                {
                    return HttpNotFound();
                }

                var querycurrentuser = from u in db.UserProfile where u.UserName == User.Identity.Name select u;
                UserProfile upr = querycurrentuser.Single();



                var query = (from g in db.Users_play where g.id_game == id where g.id_user == upr.UserId select g).Include("Users_play").Include("UserProfile");

                if (query.Count() == 0 && games.remaining_time!=0) // l'utilisateur n'a pas encore démarré cette partie 
                {
                    Users_play up = new Users_play();
                    up.id_game = id;
                    up.id_user = upr.UserId;
                    up.bomb = 3;
                    up.level = 1;
                    up.life = 3;
                    up.score = 0;


                    db.Users_play.Add(up);
                    db.SaveChanges();

                    Games_details gd = db.GetARandomEmptyPlace(up.id_game);
                    Locations lc = new Locations();
                    lc.id_user = upr.UserId;
                    lc.isauser = true;
                    lc.id_gamedet = gd.id;


                    db.Locations.Add(lc);
                    db.SaveChanges();



                }

                ViewBag.owner = new SelectList(db.UserProfile, "UserId", "UserName", games.owner);
                ViewBag.id_map = new SelectList(db.Maps, "id", "title", games.id_map);

                return View(games);
            
        }

        public void Left(int id = 0)
        {
            using (BOMBERMANEntities dbc = new BOMBERMANEntities())
            {
                Games games = dbc.Games.Find(id);
                if (games != null && games.remaining_time!=0)
                {
                    var querycurrentuser = from u in dbc.UserProfile where u.UserName == User.Identity.Name select u;
                    UserProfile upr = querycurrentuser.Single();


                   Users_play up=dbc.Users_play.Where(idg =>idg.id_game == id).Where(idu=>idu.id_user==upr.UserId).Single();
                   if (up != null && up.life > 0)
                   {
                       dbc.MoveUserToTheLeft(id, upr.UserId);
                   }
                    ServerResponse ret = new ServerResponse();
                    this.BuildServerResponseGeneralInfo(ret);
                    this.OutputServerResponse(ret);
                }

            } 

        }

        public void Right(int id = 0)
        {
            using (BOMBERMANEntities dbc = new BOMBERMANEntities())
            {
                Games games = dbc.Games.Find(id);
                if (games != null && games.remaining_time != 0)
                {
                    var querycurrentuser = from u in dbc.UserProfile where u.UserName == User.Identity.Name select u;
                    UserProfile upr = querycurrentuser.Single();

                     Users_play up=dbc.Users_play.Where(idg =>idg.id_game == id).Where(idu=>idu.id_user==upr.UserId).Single();
                     if (up != null && up.life > 0)
                     {


                         dbc.MoveUserToTheRight(id, upr.UserId);
                     }
                    ServerResponse ret = new ServerResponse();
                    this.BuildServerResponseGeneralInfo(ret);
                    this.OutputServerResponse(ret);
                }
            }
        }

        public void Up(int id = 0)
        {
            using (BOMBERMANEntities dbc = new BOMBERMANEntities())
            {
                Games games = dbc.Games.Find(id);
                if (games != null && games.remaining_time != 0)
                {
                    var querycurrentuser = from u in dbc.UserProfile where u.UserName == User.Identity.Name select u;
                    UserProfile upr = querycurrentuser.Single();

                     Users_play up=dbc.Users_play.Where(idg =>idg.id_game == id).Where(idu=>idu.id_user==upr.UserId).Single();
                     if (up != null && up.life > 0)
                     {



                         dbc.MoveUserToTheUp(id, upr.UserId);

                     }
                    ServerResponse ret = new ServerResponse();
                    this.BuildServerResponseGeneralInfo(ret);
                    this.OutputServerResponse(ret);
                }
            }

        }

        public void Down(int id = 0)
        {
            using (BOMBERMANEntities dbc = new BOMBERMANEntities())
            {
                Games games = dbc.Games.Find(id);
                if (games != null && games.remaining_time != 0)
                {
                    var querycurrentuser = from u in dbc.UserProfile where u.UserName == User.Identity.Name select u;
                    UserProfile upr = querycurrentuser.Single();

                     Users_play up=dbc.Users_play.Where(idg =>idg.id_game == id).Where(idu=>idu.id_user==upr.UserId).Single();
                     if (up != null && up.life > 0)
                     {


                         dbc.MoveUserToTheDown(id, upr.UserId);
                     }
                    ServerResponse ret = new ServerResponse();
                    this.BuildServerResponseGeneralInfo(ret);
                    this.OutputServerResponse(ret);
                }
            }

        }

        public void Bomb(int id = 0)
        {
            using (BOMBERMANEntities dbc = new BOMBERMANEntities())
            {
                Games games = dbc.Games.Find(id);
                if (games != null && games.remaining_time != 0)
                {
                    var querycurrentuser = from u in dbc.UserProfile where u.UserName == User.Identity.Name select u;
                    UserProfile upr = querycurrentuser.Single();


                     Users_play up=dbc.Users_play.Where(idg =>idg.id_game == id).Where(idu=>idu.id_user==upr.UserId).Single();
                     if (up != null && up.life > 0)
                     {

                         dbc.UserHasDroppedABomb(id, upr.UserId);
                     }
                    ServerResponse ret = new ServerResponse();
                    this.BuildServerResponseGeneralInfo(ret);
                    this.OutputServerResponse(ret);
                }
            }

        }

        public void GameInit(int id = 0)
        {
              ServerResponse ret = new ServerResponse();
             this.BuildServerResponseGeneralInfo(ret);

             this.BuildServerResponseGameInfo(ret, id);
             this.OutputServerResponse(ret);

        }



        public void ServerState(int id = 0)
        {
            ServerResponse ret = new ServerResponse();

            this.BuildServerResponseGeneralInfo(ret);
            this.BuildServerResponseGameInfo(ret, id);
            this.BuildServerResponseEntitiesInfo(ret, id);


            this.BuildServerResponseUsersInfo(ret, id);

            this.OutputServerResponse(ret);


        }





        //
        // GET: /Game/

        public ActionResult Index()
        {
           
                IList<Games> games = null;



                var query = (from g in db.Games
                             where g.UserProfile.UserName == User.Identity.Name
                             select g).Include("UserProfile").Include("Maps");

                games = query.ToList<Games>();


                return View(games);
           




        }

        //
        // GET: /Game/Details/5

        //public ActionResult Details(int id = 0)
        //{
            
        //        Games games = db.Games.Find(id);
        //        if (games == null)
        //        {
        //            return HttpNotFound();
        //        }
        //        return View(games);
            
        //}

        //
        // GET: /Game/Create

        public ActionResult Create()
        {
            
                ICollection<Maps> maps;

                var query = (from g in db.Maps
                             select g);
                maps = query.ToList<Maps>();







                ViewBag.id_map = new SelectList(maps, "id", "title");
                return View();
            
        }

        //
        // POST: /Game/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Games games)
        {
            using (BOMBERMANEntities dbc = new BOMBERMANEntities())
            {
                if (ModelState.IsValid)
                {
                    var query = from u in dbc.UserProfile where u.UserName == User.Identity.Name select u;
                    games.UserProfile = query.Single();
                    dbc.Games.Add(games);
                    dbc.SaveChanges();

                    Hashtable configuration = dbc.GetGameConfiguration(games.id);
                    int nbrows = Convert.ToInt32(configuration["MAPNUMBEROFROWS"]);

Bomberman/Controllers/GameRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bomberman.Models;

namespace Bomberman.Controllers
{
    public class GameRequestController : Controller
    {
        private BOMBERMANEntities db = new BOMBERMANEntities();

        //
        // GET: /GameRequest/

        public ActionResult Index()
        {
          //  var games_requests = db.Games_requests.Include(g => g.Games).Include(g => g.UserProfile).Include(g => g.UserProfile1);
            GameRequestReceivedSentViewModel gamerequest_receivedsent=new GameRequestReceivedSentViewModel();


          //  IList<Games_requests> games_requests = null;
            var querys = (from g in db.Games_requests
                         where g.UserProfile.UserName == User.Identity.Name
                         select g).Include("Games").Include("UserProfile").Include("UserProfile1");

            gamerequest_receivedsent.output = querys.ToList<Games_requests>();

            var queryr = (from g in db.Games_requests
                          where g.UserProfile1.UserName == User.Identity.Name
                          select g).Include("Games").Include("UserProfile").Include("UserProfile1");

            gamerequest_receivedsent.input = queryr.ToList<Games_requests>();


            return View(gamerequest_receivedsent);
        }

     

       
       

        //
        // GET: /GameRequest/Create/5

        public ActionResult Create(int id = 0)
        {

            ICollection<Games> myowngames;
            var query1 = (from g in db.Games
                          where g.UserProfile.UserName == User.Identity.Name
                          where g.remaining_time>0
                          select g);
            myowngames = query1.ToList<Games>();

            ICollection<UserProfile> players;

            var query2 = (from g in db.UserProfile
                          where g.UserName != User.Identity.Name
                          select g);
            players = query2.ToList<UserProfile>();




            ViewBag.id_game = new SelectList(myowngames, "id", "title",id);
            ViewBag.to_id_user = new SelectList(players, "UserId", "UserName");
            return View();
        }






        //
        // POST: /GameRequest/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Games_requests games_requests)
        {
            if (ModelState.IsValid)
            {
                var query = from u in db.UserProfile where u.UserName == User.Identity.Name select u;
              
                games_requests.UserProfile = query.Single();
                 
                db.Games_requests.Add(games_requests);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            IList<Games> myowngames;
            var query1 = (from g in db.Games
                          where g.UserProfile.UserName == User.Identity.Name
                          where g.remaining_time > 0
                          select g).Include("Games").Include("UserProfile");
            myowngames = query1.ToList<Games>();

            IList<UserProfile> players;

            var query2 = (from g in db.UserProfile
                          where g.UserName != User.Identity.Name
                          select g).Include("UserProfile");
            players = query2.ToList<UserProfile>();



            ViewBag.id_game = new SelectList(myowngames, "id", "title", games_requests.id_game);

            ViewBag.to_id_user = new SelectList(players, "UserId", "UserName", games_requests.to_id_user);
            return View(games_requests);
        }

      

        //
        // GET: /GameRequest/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Games_requests games_requests = db.Games_requests.Find(id);
            if (games_requests == null)
            {
                return HttpNotFound();
            }
            return View(games_requests);
        }

        //
        // POST: /GameRequest/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Games_requests games_requests = db.Games_requests.Find(id);
            db.Games_requests.Remove(games_requests);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Bomberman/Views/Game/Create.cshtml
@model Bomberman.Models.Games

@{
    ViewBag.Title = "Create";
}
<div id="main">
<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Games</legend>

        <div class="editor-label">
          Nom du jeu
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>



        <div class="editor-label">
          Temps restant
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.remaining_time)
            @Html.ValidationMessageFor(model => model.remaining_time)
        </div>

        <div class="editor-label">
            Jeu publique ?
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.is_public)
            @Html.ValidationMessageFor(model => model.is_public)
        </div>

        <div class="editor-label">
         Carte
        </div>
        <div class="editor-field">
            @Html.DropDownList("id_map", String.Empty)
            @Html.ValidationMessageFor(model => model.id_map)
        </div>

      
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to my List of games", "Index","Game") | @Html.ActionLink("Back to public games", "Index","Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</div>

Bomberman/Views/Game/Delete.cshtml
@model Bomberman.Models.Games

@{
    ViewBag.Title = "Delete";
}
<div id="main">
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Games</legend>

    <div class="display-label">
        Nom du jeu
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.title)
    </div>

    <div class="display-label">
       Temps restant
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.remaining_time)
    </div>

    <div class="display-label">
      Jeu publique ?
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.is_public)
    </div>

   
    <div class="display-label">
     Carte
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Maps.title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to my List of games", "Index","Game") | @Html.ActionLink("Back to public games", "Index","Home")
    </p>
}
    </div>

Bomberman/Views/Game/Index.cshtml
@model IEnumerable<Bomberman.Models.Games>

@{
    ViewBag.Title = "Ma liste de jeux";
}
<div id="main">
<h2>Ma liste de jeux</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th style="width:200px;">
         Nom du jeu
        </th>
        <th style="width:200px;">
          Temps restant
        </th>
        <th style="width:200px;">
           Jeu publique ?
        </th>
   
        <th style="width:200px;">Carte</th> 
        
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
         <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.remaining_time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_public)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Maps.title)
       
       
        </td>
        
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.id }) |  @Html.ActionLink("Jouons-y", "LetsPlay", new { id=item.id }) |  @Html.ActionLink("Inviter des amis", "Create","GameRequest", new {id=item.id },null) 
        </td>
    </tr>
}

</table>
    </div>

Bomberman/Views/Game/LetsPlay.cshtml
@model Bomberman.Models.Games
<script type="text/javascript" src="~/Scripts/bomberman.js"></script>


@{
    ViewBag.Title = "Details";
}

<div id="main">

<div id="remainingtime"></div>

<fieldset>
    <legend>Games</legend>

    <div class="display-label">
      Nom du jeu
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.title)
    </div>
</fieldset>
<p>
   
   @Html.ActionLink("Back to my List of games", "Index","Game") |  @Html.ActionLink("Back to public games", "Index","Home")
</p>

    <div id="users" >
                <h2 style="border:solid 1px;text-align: center;width:130px;margin-left:10px;">Users</h2>
            </div>
            <div id="listUsers" style="border: none 1px;">
                <table id="tableUsers">
                  <thead> 
                  <tr > 
                        <th style="width:40px;">ID</th> 
                        <th style="width:200px;">NAME</th> 
                        <th style="width:400px;">SCORE</th>
                        <th style="width:400px;">LIFE</th>
                        <th style="width:60px;">LEVEL</th> 
                        <th style="width:60px;">BOMB</th>
                        

                    
   


                    </tr> 
                 </thead>
                <tbody>
                
                </tbody>
                
                </table>
      </div>
    <br />



<canvas id="gamezone" width="1020px" height="1020px"></canvas>

    </div>
<script type="text/javascript">
    // démarrage de la boucle de jeu
    $.ajaxSetup({
        // Disable caching of AJAX responses
        cache: false
    });
    $(document).ready(function () {

        Game.initialize(@Model.id);

        
    });


    </script>

Bomberman/Views/Game/PublicList.cshtml
@model IEnumerable<Bomberman.Models.Games> 

@{
    Layout = "";
}
<div id="public" >
                <h2 style="border:solid 1px;text-align: center;width:130px;background-color: lightgrey ;margin-left:10px;">Jeux publiques</h2>
            </div>
            <div id="listPublic" style="border: none 1px;">
                <table id="tablePublic">
                  <thead style="text-align: right;"> 
                  <tr style="background-color:lightgrey;"> 
                      <th style="width:200px;">Nom du jeu</th> 
      <th style="width:200px;">Temps restant</th> 
      <th style="width:200px;">Carte</th> 
      
      <th style="width:400px;">Créateur</th>
     <th style="width:200px;">Jouons-y!</th>
                    </tr> 
                 </thead>
                <tbody>
                @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.remaining_time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Maps.title)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("LetsPlay", "LetsPlay", new { id=item.id }) 
            
        </td>
    </tr>
}

                </tbody>
                
                </table>
            </div>
     